services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: sa
      DB_PASSWORD: "Ram!123taty1012"
      DB_URL: jdbc:sqlserver://sqlserver:1433;databaseName=db_test;encrypt=false;trustServerCertificate=true

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Ram!123taty1012"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/1433' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5