services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: sa
      DB_PASSWORD: "Ram!123taty1012"
      DB_URL: jdbc:sqlserver://sqlserver:1433;databaseName=db_test
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - product-api-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Ram!123taty1012"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - product-api-network
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Ram!123taty1012", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  product-api-network:
    driver: bridge

volumes:
  sqlserver-data: