spring:
  datasource:
    url: jdbc:sqlserver://sqlserver:1433;databaseName=db_test;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Ram!123taty1012
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true