name: Test JMeter Action

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Verifica que los archivos estén siendo generados en la carpeta reports
      - name: List files in reports directory
        run: ls -l src/main/resources/tests
        
      - name: Run JMeter Action on a product test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: ./src/main/resources/tests/product_tests.jmx
          outputReportsFolder: ./src/main/resources/tests/reports/
          args: "--loglevel INFO"      

      - uses: actions/upload-artifact@v4
        with:
          name: jmeter-test-results
          path: reports/
