name: k6 Load Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  k6-load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Docker setup
        uses: docker/setup-compose-action@v1

      - name: Pull jdk
        run: docker pull openjdk:17-jdk-slim    
        
      - name: Docker compose up
        run: docker compose up -d
        
      - name: Esperar a que los servicios estén listos
        run: sleep 10
        
      - name: Setup k6
        uses: grafana/setup-k6-action@v1
        
      - name: Run k6 script
        run: k6 run ./k6_crud.js

      - name: Show app container logs
        run: |
          docker ps
          docker compose ps
          docker compose logs api-1

      # List contents to check if report is generated
      - name: List directory contents
        run: ls

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: reporte-k6-html
          path: ./reporte-k6.html
