name: k6 Load Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  k6-load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: '0.49.0'

      - name: Run k6 and generate JSON output
        run: k6 run --out json=resultado.json ./k6_crud.js

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install k6-reporter
        run: npm install -g k6-reporter

      - name: Generate HTML report from JSON
        run: k6-reporter resultado.json -o reporte.html

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v2
        with:
          name: reporte-k6-html
          path: reporte.html
