name: k6 Load Test

on:
  push:
    branches:
      - main

jobs:
  k6-load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: '0.49.0'

      - name: Run k6 script
        uses: grafana/run-k6-action@v1
        with:
          path: |
            ./k6_crud.js
