name: k6 Load Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  k6-load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: '0.49.0'

      - name: Run k6 script
        run: k6 run ./k6_crud.js

      - name: List directory contents
        run: ls -R

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v2
        with:
          name: reporte-k6-html
          path: reports