name: Test JMeter Action

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run JMeter Action on a product test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: recursos/tests/product_tests.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"

      # Verifica que los archivos estén siendo generados en la carpeta reports
      - name: List files in reports directory
        run: ls -l reports/

      - uses: actions/upload-artifact@v2
        with:
          name: jmeter-test-results
          path: reports/